positions: Business owner, CEO, Chairman, CIO, Co-founder, CTO, CXO, Founder, Head of, Managing director, Owner, President, VP, Vice President

keywords:
  All: service,client
  Financial Services: banking ombudsman,banking services,compensation scheme,credit bank,fca regulated,finance sector, finance sector,financial advisor,financial authority,financial compensation,financial compensation scheme,financial ombudsman service,financial qualifications,financial services,fsa register,independent financial advisor,loan,prepaid financial services,trainee financial
  Logistics and Supply Chain: cargo,carrier,cargo shipper,cargo tracking,cargo transportation,carrier local,carrier management,carriers,commercial vehicle,container,container transportation,fleet management,freight,freight broker,freight forwarding,haulage,haulage transportation,infrastructure transportation,local transportation,logistics,logistics industry,logistics management,oil management,ports transportation,railroad,retail supply,road haulage,road transport,road transportation,shipments,shipper,ships ports,ships transportation,supply chain,traffic information,transport,transport company,transportation,truck tracking,trucking,truckloads,velocity,vehicle rental
  Transportation/Trucking/Railroad: tracking,shipper,cargo,logistics,transportation,vehicle,container,shipments,ships,supply chain,traffic,transport,trucking,truckloads,velocity,vehicle
  Oil & Energy: gas,electricity,energy,supplier,source,fuel,solar,power,sustainable energy
  Real Estate: property,housing,estate,mortgage,listings,estates,lettings,house,agent

industries:
  Accounting: 47
  Airlines/Aviation: 94
  Alternative Dispute Resolution: 120
  Alternative Medicine: 125
  Animation: 127
  Apparel & Fashion: 19
  Architecture & Planning: 50
  Arts and Crafts: 111
  Automotive: 53
  Aviation & Aerospace: 52
  Banking: 41
  Biotechnology: 12
  Broadcast Media: 36
  Building Materials: 49
  Business Supplies and Equipment: 138
  Capital Markets: 129
  Chemicals: 54
  Civic & Social Organization: 90
  Civil Engineering: 51
  Commercial Real Estate: 128
  Computer & Network Security: 118
  Computer Games: 109
  Computer Hardware: 3
  Computer Networking: 5
  Computer Software: 4
  Construction: 48
  Consumer Electronics: 24
  Consumer Goods: 25
  Consumer Services: 91
  Cosmetics: 18
  Dairy: 65
  Defense & Space: 1
  Design: 99
  Education Management: 69
  E-Learning: 132
  Electrical/Electronic Manufacturing: 112
  Entertainment: 28
  Environmental Services: 86
  Events Services: 110
  Executive Office: 76
  Facilities Services: 122
  Farming: 63
  Financial Services: 43
  Fine Art: 38
  Fishery: 66
  Food & Beverages: 34
  Food Production: 23
  Fund-Raising: 101
  Furniture: 26
  Gambling & Casinos: 29
  "Glass, Ceramics & Concrete": 145
  Government Administration: 75
  Government Relations: 148
  Graphic Design: 140
  "Health, Wellness and Fitness": 124
  Higher Education: 68
  Hospital & Health Care: 14
  Hospitality: 31
  Human Resources: 137
  Import and Export: 134
  Individual & Family Services: 88
  Industrial Automation: 147
  Information Services: 84
  Information Technology and Services: 96
  Insurance: 42
  International Affairs: 74
  International Trade and Development: 141
  Internet: 6
  Investment Banking: 45
  Investment Management: 46
  Judiciary: 73
  Law Enforcement: 77
  Law Practice: 9
  Legal Services: 10
  Legislative Office: 72
  "Leisure, Travel & Tourism": 30
  Libraries: 85
  Logistics and Supply Chain: 116
  Luxury Goods & Jewelry: 143
  Machinery: 55
  Management Consulting: 11
  Maritime: 95
  Marketing and Advertising: 80
  Market Research: 97
  Mechanical or Industrial Engineering: 135
  Media Production: 126
  Medical Devices: 17
  Medical Practice: 13
  Mental Health Care: 139
  Military: 71
  Mining & Metals: 56
  Motion Pictures and Film: 35
  Museums and Institutions: 37
  Music: 115
  Nanotechnology: 114
  Newspapers: 81
  Nonprofit Organization Management: 100
  Oil & Energy: 57
  Online Media: 113
  Outsourcing/Offshoring: 123
  Package/Freight Delivery: 87
  Packaging and Containers: 146
  Paper & Forest Products: 61
  Performing Arts: 39
  Pharmaceuticals: 15
  Philanthropy: 131
  Photography: 136
  Plastics: 117
  Political Organization: 107
  Primary/Secondary Education: 67
  Printing: 83
  Professional Training & Coaching: 105
  Program Development: 102
  Public Policy: 79
  Public Relations and Communications: 98
  Public Safety: 78
  Publishing: 82
  Railroad Manufacture: 62
  Ranching: 64
  Real Estate: 44
  Recreational Facilities and Services: 40
  Religious Institutions: 89
  Renewables & Environment: 144
  Research: 70
  Restaurants: 32
  Retail: 27
  Security and Investigations: 121
  Semiconductors: 7
  Shipbuilding: 58
  Sporting Goods: 20
  Sports: 33
  Staffing and Recruiting: 104
  Supermarkets: 22
  Telecommunications: 8
  Textiles: 60
  Think Tanks: 130
  Tobacco: 21
  Translation and Localization: 108
  Transportation/Trucking/Railroad: 92
  Utilities: 59
  Venture Capital & Private Equity: 106
  Veterinary: 16
  Warehousing: 93
  Wholesale: 133
  Wine and Spirits: 142
  Wireless: 119
  Writing and Editing: 103
